//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLogs
    {
        public int LogId { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public string UserName { get; set; }
        public string LoggedFrom { get; set; }
    
        public virtual Saf Saf { get; set; }
    }
}
