//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refills
    {
        public int RefillId { get; set; }
        public string ClientCode { get; set; }
        public decimal RefillValue { get; set; }
        public string RefillBy { get; set; }
        public string Remarks { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<System.DateTime> RefillDate { get; set; }
        public Nullable<decimal> RefillRate { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> CreditsConsumed { get; set; }
    
        public virtual Saf Saf { get; set; }
    }
}
