//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSPurchases
    {
        public int Recid { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Remarks { get; set; }
        public string EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string CancelledBy { get; set; }
        public string CancelledDate { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> Supplier { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
    }
}
