//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparrowLog
    {
        public int Recid { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> MsgId { get; set; }
        public Nullable<int> Cnt { get; set; }
        public Nullable<decimal> CreditAvailable { get; set; }
        public Nullable<decimal> CreditConsumed { get; set; }
        public Nullable<long> MessageId { get; set; }
        public int ResponseCode { get; set; }
        public string ResponseMsg { get; set; }
        public string RegId { get; set; }
    }
}
