//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSGateway.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExpectedBalance
    {
        public int SupplierId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> AverageRate { get; set; }
        public Nullable<long> CreditsUsed { get; set; }
        public Nullable<long> Balance { get; set; }
    }
}
